services:
  - type: web
    name: quiz-portoex
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:CORSRequestHandler"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
